#Run file for McNemars test

reset;
option omit_zero_rows 1;
option display_eps .001;
option solution_round 3;
option solver cplex;
#option cplex_options mipgap=0.001;
model fracture.mod;
data fracture.dat;
data covariates.dat;
data outcome.dat;

problem MAX1: a, b, c, B, C, obj1,defb100, defb101, defc100, defc101, sum1, sum11, sum2, sum22, max_pair, avoid_repeat2, avoid_repeat1, pair_cons ; 
problem MIN1:  a, b, c, B, C, obj2,defb100, defb101, defc100, defc101, sum1, sum11, sum2, sum22, max_pair, avoid_repeat2, avoid_repeat1, pair_cons ; 

for{1..5}{
	
for {i in 1..T1, j in 1..T2}

		{
 
			if (CT[i,"AGE"]-CC[j,"AGE"])^2 <=36 then 

				{let  NW[i,j]:=0;}
			else
				{let  NW[i,j]:=1;}
		}

	for {i in 1..T1, j in 1..T2}

		{
			if (CT[i,"WEIGHT"]-CC[j,"WEIGHT"])^2<=36 then 

				{let  NH[i,j]:=0;}
			else
				{let  NH[i,j]:=1;}
		}

	for {i in 1..T1, j in 1..T2}

		{
			if (CT[i,"HEIGHT"]-CC[j,"HEIGHT"])^2<=36 then 

				{let  NT[i,j]:=0;}
			else
				{let  NT[i,j]:=1;}
		}
	for {i in 1..T1, j in 1..T2}

		{
			if (CT[i,"BMI"]-CC[j,"BMI"])^2<=36 then 

				{let  NB[i,j]:=0;}
			else
				{let  NB[i,j]:=1;}
		}
	
let {i in 1..T1, j in 1..T2}DD[i,j]:=NT[i,j]+NW[i,j]+NH[i,j]+NB[i,j];


	for {i in 1..T1, j in 1..T2}
		{
			if DD[i,j]=0 then 
				{let  D[i,j]:=1;}
			else
				{let  D[i,j]:=0;}
		}

		problem MAX1; 
		option solver cplex; 
		#option cplex_options mipgap=0.001;
		solve MAX1;

			printf"\n %10.3f \", n >>glow_max.txt;
			printf"\ %10.3f \", (B-C-1)/sqrt(n)>> glow_max.txt;

		problem MIN1;  
		option solver cplex; 
		#option cplex_options mipgap=0.001;
		solve MIN1;

			printf"\n %10.3f \", n >>glow_min.txt;
			printf"\ %10.3f \", (B-C-1)/sqrt(n)>> glow_min.txt;
let n:=n+1;
}
